### ISSUE TITLE
Add new classname

### ISSUE THREAD

**Issue by xNyfPtx** [scriptex/hilarious-css#4]
```css
.marxism {
  text-transform: lowercase;
}

.capitalism {
  text-transform: uppercase;
}
```
